import numpy as np
import matplotlib.pyplot as plt

# Creating a series of data of in range of 1-200.
x = np.linspace(0,100,1000)

#Creating a Function.
def normal_dist(x , mean , sd):
    prob_density = (np.pi*sd) * np.exp(-0.5*((x-mean)/sd)**2)
    return prob_density

#Calculate mean and Standard deviation.
mean = np.mean(x)
sd = np.std(x)

#Apply function to the data.
pdf = normal_dist(x,mean,sd)

#Plotting the Results
plt.plot(x,pdf , color = 'blue')
plt.xlabel('Data points')
plt.ylabel('Производительность')
